package TBS.Model;
// Generated Nov 5, 2016 4:33:28 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private String courseId;
	private String courseName;
	private String courseImgSrc;
	private String teacher;

	public Course() {
	}

	public Course(String courseId) {
		this.courseId = courseId;
	}

	public Course(String courseId, String courseName, String courseImgSrc, String teacher) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.courseImgSrc = courseImgSrc;
		this.teacher = teacher;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getCourseImgSrc() {
		return this.courseImgSrc;
	}

	public void setCourseImgSrc(String courseImgSrc) {
		this.courseImgSrc = courseImgSrc;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

}
