package TBS.Model;
// Generated Nov 9, 2016 6:36:03 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	private String question;
	private String imgSrc;
	private String optionA;
	private String optionB;
	private String optionC;
	private String optionD;
	private String answer;
	private String courseId;

	public Question() {
	}

	public Question(String courseId) {
		this.courseId = courseId;
	}

	public Question(String question, String imgSrc, String optionA, String optionB, String optionC, String optionD,
			String answer, String courseId) {
		this.question = question;
		this.imgSrc = imgSrc;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.answer = answer;
		this.courseId = courseId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getImgSrc() {
		return this.imgSrc;
	}

	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

	public String getOptionA() {
		return this.optionA;
	}

	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	public String getOptionB() {
		return this.optionB;
	}

	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	public String getOptionC() {
		return this.optionC;
	}

	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	public String getOptionD() {
		return this.optionD;
	}

	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

}
