package TBS.Model;
// Generated Dec 16, 2016 9:37:02 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Testrecord generated by hbm2java
 */
public class Testrecord implements java.io.Serializable {

	private Integer id;
	private String username;
	private String courseId;
	private Integer score;
	private Date testDate;

	public Testrecord() {
	}

	public Testrecord(String username, String courseId) {
		this.username = username;
		this.courseId = courseId;
	}

	public Testrecord(String username, String courseId, Integer score, Date testDate) {
		this.username = username;
		this.courseId = courseId;
		this.score = score;
		this.testDate = testDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

}
