package TBS.Model;
// Generated Dec 16, 2016 9:37:37 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Usercourse generated by hbm2java
 */
public class Usercourse implements java.io.Serializable {

	private UsercourseId id;

	public Usercourse() {
	}

	public Usercourse(UsercourseId id) {
		this.id = id;
	}

	public UsercourseId getId() {
		return this.id;
	}

	public void setId(UsercourseId id) {
		this.id = id;
	}

}
