package TBS.Model;
// Generated Jan 1, 2017 1:42:29 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Usercourse generated by hbm2java
 */
public class Usercourse implements java.io.Serializable {

	private Integer id;
	private String username;
	private String courseId;
	private boolean completed;

	public Usercourse() {
	}

	public Usercourse(String username, String courseId, boolean completed) {
		this.username = username;
		this.courseId = courseId;
		this.completed = completed;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public boolean isCompleted() {
		return this.completed;
	}

	public void setCompleted(boolean completed) {
		this.completed = completed;
	}

}
