package TBS.Model;
// Generated Dec 16, 2016 9:37:37 PM by Hibernate Tools 5.1.0.Beta1

/**
 * UsercourseId generated by hbm2java
 */
public class UsercourseId implements java.io.Serializable {

	private String username;
	private String courseId;
	private Boolean completed;

	public UsercourseId() {
	}

	public UsercourseId(String username) {
		this.username = username;
	}

	public UsercourseId(String username, String courseId, Boolean completed) {
		this.username = username;
		this.courseId = courseId;
		this.completed = completed;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public Boolean getCompleted() {
		return this.completed;
	}

	public void setCompleted(Boolean completed) {
		this.completed = completed;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsercourseId))
			return false;
		UsercourseId castOther = (UsercourseId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
						&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getCompleted() == castOther.getCompleted()) || (this.getCompleted() != null
						&& castOther.getCompleted() != null && this.getCompleted().equals(castOther.getCompleted())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getCompleted() == null ? 0 : this.getCompleted().hashCode());
		return result;
	}

}
